# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
# code: language=ansible
---
- name: "Create application directory {{ telegraf_path }}"
  ansible.builtin.file:
    path: "{{ telegraf_path }}"
    state: directory
    mode: 0755
  become: true

- name: "Deploy telegraf configuration"
  ansible.builtin.template:
    src:  "telegraf.conf"
    dest: "{{ telegraf_path }}/telegraf.conf"
  become: true

- name: Docker network create '{{ telegraf_docker_network }}'
  community.docker.docker_network:
    name: "{{ telegraf_docker_network }}"
    driver: bridge
    state: present
  when: telegraf_docker_network != 'host'

- name: "Start docker container {{ deployment }}-telegraf"
  community.docker.docker_container:
    name: "{{ deployment }}-telegraf"
    image: telegraf:latest
    hostname: "{{ deployment }}-telegraf"
    networks:
      - name: "{{ telegraf_docker_network }}"
    restart_policy: unless-stopped
    ports:
      - "8186:8186/tcp"
      - "8094:8094/udp"
    volumes:
      - "{{ telegraf_path }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"